sudo: false
language: erlang

otp_release:
    - 22.0.5

install:
   - wget -c https://github.com/erlang/rebar3/releases/download/3.11.1/rebar3 && chmod +x rebar3

script:
    - cd ws_server
    - REBAR3=../rebar3 make && REBAR3=../rebar3 make dialyzer && REBAR3=../rebar3 make xref
    - cd ../ws_client
    - REBAR3=../rebar3 make && REBAR3=../rebar3 make dialyzer && REBAR3=../rebar3 make xref
