sudo: false
language: erlang

otp_release:
    - 21.2.2

install:
   - wget -c https://github.com/erlang/rebar3/releases/download/3.8.0/rebar3 && chmod +x rebar3

script:
    - cd ws_server
    - REBAR3=../rebar3 make && make dialyzer && make xref
    - cd ../ws_client
    - REBAR3=../rebar3 make && make dialyzer && make xref
