sudo: false
language: erlang

otp_release:
    - 23.0.3

script:
    - cd ws_server
    - rebar3 update; make && make dialyzer && make xref
    - cd ../ws_client
    - make && make dialyzer && make xref
