version: 2
jobs:
  build:
    docker:
      - image: erlang:23.1.0.0
    steps:
      - checkout
      - run:
          name: change ws_server directory, make
          command: cd ws_server/ && make && make dialyzer && make xref
      - run:
          name: change ws_client directory, make
          command: cd ws_client/ && make && make dialyzer && make xref
