version: 2
jobs:
  build:
    docker:
      - image: erlang:21.2.7
    steps:
      - checkout
      - run:
          name: download rebar3
          command: wget -c https://github.com/erlang/rebar3/releases/download/3.9.0/rebar3 && chmod +x rebar3
      - run:
          name: change ws_server directory, make
          command: cd ws_server/ && REBAR3=../rebar3 make && make dialyzer && make xref
      - run:
          name: change ws_client directory, make
          command: cd ws_client/ && REBAR3=../rebar3 make && make dialyzer && make xref
