name: ci
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: copmile the source code
    # This job runs on Linux
    runs-on: ubuntu-latest

    container:
     image: erlang:23.0.2

    steps:
      - uses: actions/checkout@v1.0.0
      - name: download rebar3 and make
        run: |
         cd ws_server
         make
         make dialyzer
         make xref
         cd ../ws_client
         make
         make dialyzer
         make xref
